version: "3.8"
services:
  ratio-nginx:
    image: nginx:1.19-alpine
    container_name: 'ratio-nginx-nginx'
    volumes:
      - ./server:/var/www/server
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - ratio-server
  ratio-postgres:
    image: postgres:12-alpine
    container_name: 'ratio-postgres'
    restart: always
    volumes:
      - ./etc/postgres/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: ratio-user
      POSTGRES_PASSWORD: ratio-password
      POSTGRES_DB: ratio
    ports:
        - 5432:5432
  ratio-server:
    build: ./server
    container_name: 'ratio-server'
    volumes:
      - ./server:/var/www/server
    depends_on:
      - ratio-postgres
      - ratio-rabbit
      - ratio-redis
  ratio-rabbit:
    image: rabbitmq:3-management-alpine
    container_name: 'ratio-rabbit'
    environment:
        RABBITMQ_DEFAULT_USER: ratio-user
        RABBITMQ_DEFAULT_PASS: ratio-password
    ports:
        - 5672:5672
        - 15672:15672
  ratio-redis:
    image: redis:6-alpine
    container_name: 'ratio-redis'
    ports:
        - 6379:6379
