name: '{project_name}'

services:
  go:
    container_name: go-{project_name}
    build:
      context: ./
    volumes:
      - ../app:/app
    # ports:
    #  - '80:80'
    networks:
      - go_{project_name}

networks:
  go_{project_name}:
    driver: bridge