name: '{NAME_PROJECT}'

services:
  go:
    container_name: go-{NAME_PROJECT}
    build:
      context: ./
    volumes:
      - ../app:/app
    # ports:
    #  - '80:80'
    networks:
      - go_{NAME_PROJECT}

networks:
  go_{NAME_PROJECT}:
    driver: bridge